In [2]:
import torch

To initialize a tensor, we can use the `torch.Tensor()` function. This function takes in a list of numbers and returns a tensor object.

In [33]:
t = torch.Tensor([ 1, 2, 3])

print(t)
print(t.shape)

tensor([1., 2., 3.])
torch.Size([3])


Adding a dimension to a tensor. This is useful when you want to add a batch dimension to a single image for example, since a model usually expects batches.

`[:, None]` is a Python syntax for adding a dimension. `None` is a special Python object that indicates that this dimension should be added.

In [34]:
t = t[:, None]

print(t)
print(t.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


Transpose of a tensor: `t.t()`

In [ ]:
t = t.t()

print(t)
print(t.shape)

tensor([[1., 2., 3.]])
torch.Size([1, 3])


The `@` operator performs matrix multiplication between two tensors.

In [43]:
t1 = torch.Tensor([1, 2, 3])
t2 = torch.Tensor([4, 5, 6])

t1 @ t2 # dot product or inner product - implicit

tensor(32.)

In [47]:
# Explicitly, manually transposing t1 and multiplying by t2
t1.t()  @ t2

tensor(32.)

In [45]:
# Explicitly, using torch.dot
torch.dot(t1, t2)

tensor(32.)

In [46]:
# Explicitly, using torch.matmul
torch.matmul(t1, t2)

tensor(32.)

---

In [2]:
import torch
# Softmax
def softmax(x):
    return torch.exp(x) / torch.exp(x).sum()

x = torch.Tensor([1.0, 2.0, 3.0])
softmax(x)


tensor([0.0900, 0.2447, 0.6652])

In [5]:
softmax(x+2)

tensor([0.0900, 0.2447, 0.6652])

In [16]:
def polynomial(x):
    return x**4 - 2 * x**3 + 3 * x**2 - 4 * x + 5

# MODIFY THE CODE BELOW TO DEFINE p1, p2, p3, p4 and d2y_x, d3y_x, and d4y_x

def p1(x):
    # TODO: fix me to be the derivative of polynomial(x)
    return 4 * x**3 - 6 * x**2 + 6 * x - 4

def p2(x):
    # TODO: fix me to be the derivative of p1(x)
    return 12 * x**2 - 12 * x + 6

def p3(x):
    # TODO: fix me to be the derivative of p2(x)
    return 24 * x - 12
def p4(x):
    # TODO: fix me to be the derivative of p3(x)
    return 24

 # TODO: fix me by adding requires_grad
x = torch.linspace(-2.0, 3.0, 100, requires_grad=True)
y = polynomial(x, requires_grad=True)

TypeError: polynomial() got an unexpected keyword argument 'requires_grad'

In [17]:
# torch.autograd.grad(y.sum(), [x])  # TODO: fix me to be the derivative of y.sum() w.r.t. to x
[dy_dx] = [torch.autograd.grad(y.sum(), [x])] 
# TODO: fix me to be the 2st derivative of y.sum() w.r.t. to x
[d2y_dx] = [torch.autograd.grad(dy_dx.sum(), [x])]
[d3y_dx] = [torch.autograd.grad(d2y_dx.sum(), [x])]
[d4y_dx] = [torch.autograd.grad(d3y_dx.sum(), [x])]

# DO NOT CHANGE THE PLOTTING CODE OR TESTS BELOW

import matplotlib.pyplot as plt
fig, [ax1, ax2] = plt.subplots(1, 2, figsize=(12,4), sharey=True)

with torch.no_grad():
    ax1.set_title('Power rule')
    for i in range(0, 5):
        ax1.plot(x, [polynomial, p1, p2, p3, p4][i](x), label=f'$p_{i}(x)$')
    ax1.legend()
    ax2.set_title('Autograd')
    ax2.plot(x, y, label='$y$')
    ax2.plot(x, dy_dx, label='$dy/dx$')
    for i in [2, 3, 4]:
        ax2.plot(x, [d2y_dx, d3y_dx, d4y_dx][i-2], label=f'$d^{i}y/dx$')
    ax2.legend()

assert(all((p1(x) - dy_dx).abs() < 1e-5))
assert(all((p2(x) - d2y_dx).abs() < 1e-5))
assert(all((p3(x) - d3y_dx).abs() < 1e-5))
assert(all((p4(x) - d4y_dx).abs() < 1e-5))


RuntimeError: One of the differentiated Tensors appears to not have been used in the graph. Set allow_unused=True if this is the desired behavior.