In [2]:
import torch

To initialize a tensor, we can use the `torch.Tensor()` function. This function takes in a list of numbers and returns a tensor object.

In [33]:
t = torch.Tensor([ 1, 2, 3])

print(t)
print(t.shape)

tensor([1., 2., 3.])
torch.Size([3])


Adding a dimension to a tensor. This is useful when you want to add a batch dimension to a single image for example, since a model usually expects batches.

`[:, None]` is a Python syntax for adding a dimension. `None` is a special Python object that indicates that this dimension should be added.

In [34]:
t = t[:, None]

print(t)
print(t.shape)

tensor([[1.],
        [2.],
        [3.]])
torch.Size([3, 1])


Transpose of a tensor: `t.t()`

In [ ]:
t = t.t()

print(t)
print(t.shape)

tensor([[1., 2., 3.]])
torch.Size([1, 3])


The `@` operator performs matrix multiplication between two tensors.

In [43]:
t1 = torch.Tensor([1, 2, 3])
t2 = torch.Tensor([4, 5, 6])

t1 @ t2 # dot product or inner product - implicit

tensor(32.)

In [47]:
# Explicitly, manually transposing t1 and multiplying by t2
t1.t()  @ t2

tensor(32.)

In [45]:
# Explicitly, using torch.dot
torch.dot(t1, t2)

tensor(32.)

In [46]:
# Explicitly, using torch.matmul
torch.matmul(t1, t2)

tensor(32.)

---